#!/usr/bin/env bash

set -euo pipefail

git submodule foreach --recursive git status --porcelain

git submodule foreach --recursive git reset --hard

git submodule foreach --recursive git clean --directory --force --exclude

git submodule update --init --recursive
