name: Build & Test
"on":
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: pages
  cancel-in-progress: false
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          submodules: recursive
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@75d2e84710de30f6ff7268e08f310b60ef14033f # v3
        with:
          extended: true
      - name: Build Site
        run: |
          # Create root level .nojekyll
          touch .nojekyll
          # Build site directly in repo root
          hugo new site . --force
          git submodule add --depth=1 https://github.com/adityatelange/hugo-PaperMod.git themes/PaperMod
          cat > hugo.toml <<EOF
          baseURL = "https://gkwa.github.io/hardsing/"
          title = "My New Hugo Site"
          theme = "PaperMod"

          [params]
          homeInfoParams = { Title = "Welcome 👋", Content = "My Hugo blog" }
          EOF
          # Create test content
          hugo new content posts/my-first-post.md
          echo '---
          title: "My First Post"
          date: 2024-11-13
          ---
          Welcome to my first post!' > content/posts/my-first-post.md

          # Build site
          hugo --minify

          # Add .nojekyll to public
          touch public/.nojekyll
      - name: Upload artifact
        uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # v3
        with:
          path: ./public
  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4
